Change "statement" to "step" in UI
expln/metamath-lamp pull request #88
Opened 2023-06-10 14:02 UTC by david-a-wheeler

We recently agreed that it'd be clearer in the UI if we said that there were many *steps*, and each step contained a *statement*. This commit modifies the UI to more consistently say "step" when step is what was intended. Renaming "statement" to "step" everywhere in the UI would be incorrect, as in many cases "statement" is intended. I also changed "id" to "label" in a few places, again, for consistency.

There are probably a few missed spots, which will have to be fixed by future commits, but this at least gets things started.

This does *not* try to rename anything in the code, just the UI.

2023-06-10 14:06 UTC, david-a-wheeler commented
@expln - surprise! :-) . Here's a PR on metamath-lamp, that tries to switch UI displays from "statement" to "step" when "step" was meant. You can't do a global search-and-replace on the UI, because sometimes statement *is* meant, while in other cases the whole step (including its statement) is meant.

2023-06-10 21:20 UTC, expln requested changes
Yes, indeed, this is a surprise for me :)

In general everything is fine. I left few comments where I asked not to change `label` to `id` and in some places I think usage of `statement` is more correct. Please check.

2023-06-10 21:20 UTC, expln commented on src/metamath/worker/MM_wrk_editor.res
> +        | None => Error(`Cannot find a step with label = '${id1}'`)
`Cannot find a step with label = '${id1}'`

That's ok to change `statement` to `step` here, but let's not change `id` to `label`. That would be very misleading if I see `Cannot find a step with label = '1'` because actually label could be different. id1 variable in the code is an internal id. It is different from a label. But it is not exposed to users. Therefore I think this message is also a technical, however I am not sure, because it is not in raise(MmException(...)).

2023-06-10 21:20 UTC, expln commented on src/metamath/worker/MM_wrk_editor.res
> +                | None => Error(`Cannot find a step with label = '${id2}'`)
`Cannot find a step with label = '${id2}'`

Same here - that's ok to change `statement` to `step`, but let's not change `id` to `label`.

2023-06-10 22:22 UTC, david-a-wheeler commented on src/metamath/ui/MM_cmp_settings.res
> +            title="This text is used as initial content for new steps"
I agree, thanks for pointing out the error!

I see that we agree with this distinction between "statement types" and "step types",. This is easier to explain when you distinguish statements and steps :-).

2023-06-10 22:25 UTC, david-a-wheeler commented on src/metamath/worker/MM_wrk_editor.res
> +                        {...stmt, stmtErr:Some(`This step is the same as the previously defined`
Ah, that's a great point! I agree, will revert.

2023-06-10 22:38 UTC, david-a-wheeler commented
Thanks for the review! I made the changes you requested.

2023-06-10 22:39 UTC, david-a-wheeler commented
My *hope* is that my PR will give you more time to do other awesome things :-).

2023-06-11 05:05 UTC, expln approved these changes
Everything looks good. Thanks for helping me with this renaming!

2023-06-11 05:06 UTC, merged